add GPDB 6X centos7 FIPS python regression test
For Greenplum 6X on centos7 in a FIPS enabled environment our python
utilities would log the following error.

ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/greenplum-db-devel/ext/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/greenplum-db-devel/ext/python/lib/python2.7/hashlib.py", line 109, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/usr/local/greenplum-db-devel/ext/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5

This adds a regression test and was inspired from the following 5X
commit b07b2a23.

Co-authored-by: Mark Sliva <msliva@pivotal.io>

diff --git a/concourse/pipelines/gpdb_6X_STABLE-generated.yml b/concourse/pipelines/gpdb_6X_STABLE-generated.yml
--- a/concourse/pipelines/gpdb_6X_STABLE-generated.yml
+++ b/concourse/pipelines/gpdb_6X_STABLE-generated.yml
@@ -12,7 +12,7 @@
 ## file (example: templates/gpdb-tpl.yml) and regenerate the pipeline
 ## using appropriate tool (example: gen_pipeline.py -t prod).
 ## ----------------------------------------------------------------------
-## Generated by gen_pipeline.py at: 2020-05-14 18:43:20.505445
+## Generated by gen_pipeline.py at: 2020-05-15 13:34:28.229103
 ## Template file: gpdb-tpl.yml
 ## OS Types: ['centos6', 'centos7', 'ubuntu18.04', 'win']
 ## Test Sections: ['ICW', 'Replication', 'ResourceGroups', 'Interconnect', 'CLI', 'UD', 'AA', 'Extensions', 'Gpperfmon']
@@ -177,6 +177,7 @@ groups:
   - icw_gporca_centos6
   - icw_planner_centos6
   - icw_planner_ictcp_centos6
+  - fips_centos7
   - gpexpand
   - pg_upgrade
   - icw_gporca_centos7
@@ -266,6 +267,7 @@ groups:
   - icw_planner_centos6
   - icw_planner_ictcp_centos6
   - compile_gpdb_centos6
+  - fips_centos7
   - pg_upgrade
   - icw_gporca_centos7
   - icw_planner_centos7
@@ -1154,6 +1156,74 @@ jobs:
         MAKE_TEST_COMMAND: -k PGOPTIONS='-c optimizer=off' installcheck-world
         TEST_OS: ubuntu
         CONFIGURE_FLAGS: {{configure_flags}}
+
+
+- name: fips_centos7
+  plan:
+  - in_parallel:
+    - get: gpdb_src
+      passed: [compile_gpdb_centos7]
+    - get: gpdb_binary
+      resource: bin_gpdb_centos7
+      passed: [compile_gpdb_centos7]
+      trigger: true
+    - get: ccp_src
+    - get: ccp-image
+  - put: terraform
+    params:
+      action: create
+      delete_on_failure: true
+      generate_random_name: true
+      terraform_source: ccp_src/google/
+      vars:
+        PLATFORM: centos7
+        boot_disk_image: data-gp-toolsmiths/gpdb-prod-centos-7-fips
+        instance_type: n1-standard-2
+  - task: gen_cluster
+    file: ccp_src/ci/tasks/gen_cluster.yml
+    params:
+      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
+      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
+      AWS_DEFAULT_REGION: {{aws-region}}
+      BUCKET_PATH: clusters-google/
+      BUCKET_NAME: {{tf-bucket-name}}
+      CLOUD_PROVIDER: google
+      PLATFORM: centos7
+  - task: gpinitsystem
+    file: ccp_src/ci/tasks/gpinitsystem.yml
+  - task: test_fips
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source:
+          repository: pivotaldata/ccp
+          tag: "7"
+      inputs:
+        - name: ccp_src
+        - name: cluster_env_files
+      run:
+        path: bash
+        args:
+          - -c
+          - |
+            set -e
+
+            ccp_src/scripts/setup_ssh_to_cluster.sh
+            ssh -t mdw <<EOF
+                set -e
+
+                # python regression test for "ERROR:root:code for hash md5 was not found."
+                if ! python -c "import hashlib"; then
+                    echo "Failed to import hashlib on a FIPS enabled environment."
+                    exit 1
+                fi
+                echo "Successfully imported hashlib on a FIPS enabled environment."
+            EOF
+    on_success:
+      <<: *ccp_destroy
+  ensure:
+    <<: *set_failed
 
 - name: gate_icw_end
   plan:
@@ -3219,6 +3289,7 @@ jobs:
         - gpexpand
         - check_centos
         - interconnect
+        - fips_centos7
       - get: bin_gpdb_centos6
         trigger: true
         passed:
diff --git a/concourse/pipelines/templates/gpdb-tpl.yml b/concourse/pipelines/templates/gpdb-tpl.yml
--- a/concourse/pipelines/templates/gpdb-tpl.yml
+++ b/concourse/pipelines/templates/gpdb-tpl.yml
@@ -204,6 +204,7 @@ groups:
   - icw_gporca_centos6
   - icw_planner_centos6
   - icw_planner_ictcp_centos6
+  - fips_centos7
 {% endif %}
 {% if "centos6" in os_types and "CLI" in test_sections %}
   - gpexpand
@@ -311,6 +312,7 @@ groups:
   - icw_planner_centos6
   - icw_planner_ictcp_centos6
   - compile_gpdb_centos6
+  - fips_centos7
 {% endif %}
 {% if "centos6" in os_types and "CLI" in test_sections %}
   - pg_upgrade
@@ -1274,6 +1276,76 @@ jobs:
         CONFIGURE_FLAGS: {{configure_flags}}
 
 {% endif %}
+
+{% if "centos7" in os_types %}
+- name: fips_centos7
+  plan:
+  - in_parallel:
+    - get: gpdb_src
+      passed: [compile_gpdb_centos7]
+    - get: gpdb_binary
+      resource: bin_gpdb_centos7
+      passed: [compile_gpdb_centos7]
+      trigger: true
+    - get: ccp_src
+    - get: ccp-image
+  - put: terraform
+    params:
+      action: create
+      delete_on_failure: true
+      generate_random_name: true
+      terraform_source: ccp_src/google/
+      vars:
+        PLATFORM: centos7
+        boot_disk_image: data-gp-toolsmiths/gpdb-prod-centos-7-fips
+        instance_type: n1-standard-2
+  - task: gen_cluster
+    file: ccp_src/ci/tasks/gen_cluster.yml
+    params:
+      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
+      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
+      AWS_DEFAULT_REGION: {{aws-region}}
+      BUCKET_PATH: clusters-google/
+      BUCKET_NAME: {{tf-bucket-name}}
+      CLOUD_PROVIDER: google
+      PLATFORM: centos7
+  - task: gpinitsystem
+    file: ccp_src/ci/tasks/gpinitsystem.yml
+  - task: test_fips
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source:
+          repository: pivotaldata/ccp
+          tag: "7"
+      inputs:
+        - name: ccp_src
+        - name: cluster_env_files
+      run:
+        path: bash
+        args:
+          - -c
+          - |
+            set -e
+
+            ccp_src/scripts/setup_ssh_to_cluster.sh
+            ssh -t mdw <<EOF
+                set -e
+
+                # python regression test for "ERROR:root:code for hash md5 was not found."
+                if ! python -c "import hashlib"; then
+                    echo "Failed to import hashlib on a FIPS enabled environment."
+                    exit 1
+                fi
+                echo "Successfully imported hashlib on a FIPS enabled environment."
+            EOF
+    on_success:
+      <<: *ccp_destroy
+  ensure:
+    <<: *set_failed
+{% endif %}
+
 - name: gate_icw_end
   plan:
   - in_parallel:
@@ -2128,6 +2200,7 @@ jobs:
         - gpexpand
         - check_centos
         - interconnect
+        - fips_centos7
       - get: bin_gpdb_centos6
         trigger: true
         passed:
