Update gpdb_6X_STABLE-generated.yml changes
After add fips support for 6X_STABLE

Authored-by: Shaoqi Bai <bshaoqi@vmware.com>

diff --git a/concourse/pipelines/gpdb_6X_STABLE-generated.yml b/concourse/pipelines/gpdb_6X_STABLE-generated.yml
--- a/concourse/pipelines/gpdb_6X_STABLE-generated.yml
+++ b/concourse/pipelines/gpdb_6X_STABLE-generated.yml
@@ -12,7 +12,7 @@
 ## file (example: templates/gpdb-tpl.yml) and regenerate the pipeline
 ## using appropriate tool (example: gen_pipeline.py -t prod).
 ## ----------------------------------------------------------------------
-## Generated by gen_pipeline.py at: 2023-01-13 16:14:27.057401
+## Generated by gen_pipeline.py at: 2023-01-28 20:48:55.887385
 ## Template file: gpdb-tpl.yml
 ## OS Types: 
 ## Test Sections: ['ICW', 'Replication', 'ResourceGroups', 'Interconnect', 'CLI', 'UD', 'AA', 'Extensions', 'Gpperfmon']
@@ -185,6 +185,8 @@ groups:
   - icw_planner_icproxy_rocky8
   - icw_planner_ictcp_rocky8
   - icw_mirrorless_rocky8
+  # Not support enable fips on ubuntu18.04
+  - fips_rocky8
   - unit_tests_gporca_rocky8
   - gpdb_pitr_rocky8
   - gate_icw_end
@@ -258,6 +260,7 @@ groups:
   - icw_mirrorless_rocky8
   - compile_gpdb_rocky8
   - unit_tests_gporca_rocky8
+  - fips_rocky8
   - pg_upgrade_rocky8
   - gate_icw_end
 
@@ -1093,6 +1096,78 @@ jobs:
         WITH_MIRRORS: true
         TEST_OS: centos
         CONFIGURE_FLAGS: ((configure_flags))
+
+- name: fips_rocky8
+  plan:
+  - in_parallel:
+    - get: gpdb_src
+      passed: [compile_gpdb_rocky8]
+    - get: gpdb_binary
+      resource: bin_gpdb_rocky8
+      passed: [compile_gpdb_rocky8]
+      trigger: true
+    - get: ccp_src
+    - get: ccp-image
+    - get: terraform.d
+      params:
+        unpack: true
+  - put: terraform
+    params:
+      action: create
+      delete_on_failure: true
+      generate_random_name: true
+      plugin_dir: ../../terraform.d/plugin-cache/linux_amd64
+      terraform_source: ccp_src/google/
+      vars:
+        PLATFORM: rocky8-fips
+        instance_type: n1-standard-2
+  - task: gen_cluster
+    file: ccp_src/ci/tasks/gen_cluster.yml
+    params:
+      AWS_ACCESS_KEY_ID: ((tf-machine-access-key-id))
+      AWS_SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
+      AWS_DEFAULT_REGION: ((aws-region))
+      BUCKET_PATH: clusters-google/
+      BUCKET_NAME: ((tf-bucket-name))
+      CLOUD_PROVIDER: google
+      PLATFORM: rocky8-fips
+  - task: gpinitsystem
+    file: ccp_src/ci/tasks/gpinitsystem.yml
+    params:
+      PLATFORM: rocky8-fips
+  - task: test_fips
+    config:
+      platform: linux
+      image_resource:
+        type: registry-image
+        source:
+          repository: gcr.io/data-gpdb-public-images/ccp
+          tag: "latest"
+      inputs:
+        - name: ccp_src
+        - name: cluster_env_files
+      run:
+        path: bash
+        args:
+          - -c
+          - |
+            set -e
+
+            ccp_src/scripts/setup_ssh_to_cluster.sh
+            ssh -t cdw <<EOF
+                set -e
+                cat /proc/sys/crypto/fips_enabled
+                # python regression test for "ERROR:root:code for hash md5 was not found."
+                if ! python -c "import hashlib"; then
+                    echo "Failed to import hashlib on a FIPS enabled environment."
+                    exit 1
+                fi
+                echo "Successfully imported hashlib on a FIPS enabled environment."
+            EOF
+    on_success:
+      <<: *ccp_destroy
+  ensure:
+    <<: *set_failed
 
 - name: gate_icw_end
   plan:
@@ -2536,6 +2611,7 @@ jobs:
         - pg_upgrade_rocky8
         - gpexpand_rocky8
         - check_rocky8
+        - fips_rocky8
       - get: bin_gpdb_rocky8
         trigger: true
         passed:
