Add configure and build scripts run

diff --git a/.github/workflows/build-gpdb.yml b/.github/workflows/build-gpdb.yml
--- a/.github/workflows/build-gpdb.yml
+++ b/.github/workflows/build-gpdb.yml
@@ -267,6 +267,30 @@ jobs:
             echo "- GCC Version: $(gcc --version | head -n1)"
           } >> "$GITHUB_STEP_SUMMARY"
 
+      - name: Run Greenplum configure script
+        env:
+          SRC_DIR: ${{ github.workspace }}
+        run: |
+          set -eo pipefail
+          chmod +x "${SRC_DIR}"/../gpdb-devops/build_automation/gpdb/scripts/configure-gpdb.sh
+          cd ${SRC_DIR}
+          if ! SRC_DIR=${SRC_DIR} ENABLE_DEBUG=${{ env.ENABLE_DEBUG }} ${SRC_DIR}/../gpdb-devops/build_automation/gpdb/scripts/configure-gpdb.sh; then
+            echo "::error::Configure script failed"
+            exit 1
+          fi
+
+      - name: Run Greenplum build script
+        env:
+          SRC_DIR: ${{ github.workspace }}
+        run: |
+          set -eo pipefail
+          chmod +x "${SRC_DIR}"/../gpdb-devops/build_automation/gpdb/scripts/build-gpdb.sh
+          cd ${SRC_DIR}
+          if ! SRC_DIR=${SRC_DIR} ${SRC_DIR}/../gpdb-devops/build_automation/gpdb/scripts/build-gpdb.sh; then
+            echo "::error::Build script failed"
+            exit 1
+          fi
+
       - name: Run Greenplum debian package build script
         env:
           SRC_DIR: ${{ github.workspace }}
