Mount runner-host dirs to container

diff --git a/.github/workflows/build-gpdb.yml b/.github/workflows/build-gpdb.yml
--- a/.github/workflows/build-gpdb.yml
+++ b/.github/workflows/build-gpdb.yml
@@ -721,6 +721,8 @@ jobs:
         --privileged
         --user root
         --cgroupns=private
+      volumes:
+        - /:/host_volume
 
     steps:
       - name: Use timestamp from previous job
@@ -745,31 +747,26 @@ jobs:
 
       - name: Free disk space
         run: |
+          set -ex pipefail
+
+          # Remove some host directories
           rm -rf \
-            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
-            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
-            /usr/lib/jvm || true
-          echo "some directories deleted"
-          apt install aptitude -y >/dev/null 2>&1
-          aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync \
-            esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
-            google-cloud-sdk imagemagick \
-            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
-            mercurial apt-transport-https mono-complete libmysqlclient \
-            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
-            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
-            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
-            sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable \
-            -y -f >/dev/null 2>&1
-          aptitude purge google-cloud-sdk -f -y >/dev/null 2>&1
-          aptitude purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
-          apt purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
-          aptitude purge '~n ^mysql' -f -y >/dev/null 2>&1
-          aptitude purge '~n ^php' -f -y >/dev/null 2>&1
-          aptitude purge '~n ^dotnet' -f -y >/dev/null 2>&1
-          apt-get autoremove -y >/dev/null 2>&1
-          apt-get autoclean -y >/dev/null 2>&1
-          echo "some packages purged"
+            /host_volume/usr/share/dotnet /host_volume/usr/local/lib/android /host_volume/opt/ghc \
+            /host_volume/usr/local/share/powershell /host_volume/usr/share/swift /host_volume/usr/local/.ghcup \
+            /host_volume/usr/lib/jvm || true
+
+          # Remove unused packages and dependencies
+          apt-get autoremove -y
+          apt-get clean -y
+
+          # Remove cached files
+          rm -rf /var/lib/apt/lists/*
+
+          # Clean up temporary files
+          rm -rf /tmp/*
+
+          # Optionally, check disk usage
+          df -h
 
       - name: Environment Initialization
         if: needs.check-skip.outputs.should_skip != 'true'
@@ -795,19 +792,6 @@ jobs:
 
           df -h | tee -a "${LOGS_DIR}/details/disk-usage.log"
           free -h | tee -a "${LOGS_DIR}/details/memory-usage.log"
-
-          # Remove unused packages and dependencies
-          apt-get autoremove -y
-          apt-get clean -y
-
-          # Remove cached files
-          rm -rf /var/lib/apt/lists/*
-
-          # Clean up temporary files
-          rm -rf /tmp/*
-
-          # Optionally, check disk usage
-          df -h
 
           {
             echo "=== Environment Information ==="
