Add upload debian packages to releases

diff --git a/.github/workflows/build-gpdb.yml b/.github/workflows/build-gpdb.yml
--- a/.github/workflows/build-gpdb.yml
+++ b/.github/workflows/build-gpdb.yml
@@ -529,7 +529,7 @@ jobs:
 
   deb-install-test:
     name: Deb install test (${{ matrix.name }})
-    needs: [build]
+    needs: [prepare-build-matrix, build]
     runs-on: ubuntu-latest
     timeout-minutes: 120
 
@@ -1417,3 +1417,39 @@ jobs:
           echo "Timestamp: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
           echo "Build Result: ${{ needs.build.result }}"
           echo "Test Result: ${{ needs.test.result }}"
+
+  ## ======================================================================
+  ## Job: upload_debian
+  ## ======================================================================
+
+  upload_debian:
+    if: startsWith(github.ref_name , 'refs/tags/')
+    runs-on: ubuntu-latest
+    name: Upload Debian Package
+    needs: [build, deb-install-test]
+    permissions:
+      contents: write
+    steps:
+      - name: Download Greenplum debian build artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: debian-packages-build
+          path: ${{ github.workspace }}/deb_build_artifacts
+          merge-multiple: false
+
+      - name: Verify DEB artifacts
+        id: verify-artifacts
+        run: |
+          set -ex pipefail
+          DEB_FILE=$(ls "${GITHUB_WORKSPACE}"/deb_build_artifacts/*.deb)
+          if [ ! -f "${DEB_FILE}" ]; then
+            echo "::error::DEB file not found"
+            exit 1
+          fi
+          echo "deb_file=${DEB_FILE}" >> "$GITHUB_OUTPUT"
+      - name: Upload Release Asset
+        uses: softprops/action-gh-release@v2
+        with:
+          token: ${{ github.token }}
+          tag_name: ${{ github.ref_name }}
+          files: ${{ steps.verify-artifacts.outputs.deb_file }}
